config_ignore_collection.settings:
  path: '/admin/config/development/configuration/ignorecollection'
  defaults:
    _form: '\Drupal\config_ignore_collection\Form\Settings'
    _title: 'Ignore Collections'
  requirements:
    _permission: 'import configuration'
