config_ignore_collection.settings:
  type: config_object
  label: 'Config Collections Ignore'
  mapping:
    ignored_config_collections:
      type: sequence
      label: 'List of ignored collections of configurations'
      sequence:
        type: string
